# Generated by Django 5.1.1 on 2024-09-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_favorite',
        ),
    ]
